
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: install all required dependencies
    apt: 
      apk:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb