- 
    name: update repositories
    hosts: all_nodes
    vars:
      pkgs:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
    
    tasks:
      - name: update repos
        apt:
          update_cache: yes
          
      - name: install all required dependencies
        apt: name={{ pkgs }} update_cache=yes state=latest
      
-
    name: Deploy a web application
    hosts: web1   
    tasks:
      - name: Install python flask dependency
        pip:
          name: "{{ item }}"
          state: present
        with_items:
            - flask
            - flask-mysql
-
    name: Install MySQL server database
    hosts: dbe1
    vars:
      pkgs:
          - mysql-server
          - mysql-client
    tasks:
      - name: install all required dependencies
        apt: name={{ pkgs }} update_cache=yes state=latest

      - name: Start mysql server
        service:
          name: mysql
          state: started
          enabled: yes

      - name: Create Application Database
        mysql_db:
          name: employed_db
          state: present         

      - name: Create Database user
        mysql_user:
            name: db_user
            password: Passw0rd
            priv: '*.*:ALL'
            state: present
            host: '%'
-
    name: Run app
    hosts: web1
    tasks:
      - name: copy source code
        copy: src=app.py dest=/opt/app.py

      - name: start web server
        shell: FLASK_APP=app.py nohoup flask run --host=0.0.0.0 &
